#!/bin/bash
echo "═══════════════════════════════════════════"
echo "  Verificación de Seven Travels"
echo "═══════════════════════════════════════════"
echo ""
echo "✅ Tu sitio ESTÁ funcionando en:"
echo "   https://marcosaquino84.github.io/-seven-travels/"
echo ""
echo "Si ves 404, prueba:"
echo ""
echo "1. Limpia la caché: Ctrl + Shift + R"
echo "2. Modo incógnito: Ctrl + Shift + N"
echo "3. Espera 2-3 minutos más"
echo ""
echo "Verificar estado en GitHub:"
echo "   https://github.com/MarcosAquino84/-seven-travels/settings/pages"
echo ""
echo "Debe decir:"
echo "   'Your site is live at https://marcosaquino84.github.io/-seven-travels/'"
echo ""
echo "═══════════════════════════════════════════"
